# -*- coding: utf-8 -*-
"""Data Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9c7II-54lfXqJFvYUnTsg6g9ZR6VeKd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

headers = ["District", "Year", "Month\Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
           "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
           "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "Janina"]

df = pd.read_excel("D:\Trimester - 2\OOP Lab\Project\Data Set\Copy of Daily  Max  Temp Till Jun_2014.xls", names = headers)

df1 = df.copy()

df1.head(10)

"""Deleted the first 7 rows as they don't have any valuable data."""

df1.drop(df1.head(7).index, inplace= True)
df1.drop('Janina', axis=1, inplace=True)

df1.shape

df1.head(10)

"""Locating a district and making a separate dataset of it"""

bogra = df1.loc[df1["District"] == "Bogra"]
bogra

"""Replacing the 1234s with month names"""

replace_values = {1:"January", 2:"February", 3:"March", 4:"April", 5:"May",
                  6:"June", 7:"July", 8:"August", 9:"September", 10:"October",
                  11:"November", 12:"December"}

bogra["Month\Date"] = bogra["Month\Date"].replace(replace_values)
bogra

"""## Dealing With Nul Values"""

# replacing "****" with NaN
bogra.replace("****", np.nan, inplace = True)
bogra

# evaluating missing data (Boolian value)
missing_data = bogra.isnull()
missing_data

bogra.describe()

bogra_1948 = bogra.loc[bogra["Year"] == 1948].reset_index(drop = True)
bogra_1948

bogra_1948['Tempareture of the month'] = bogra_1948.iloc[:, 3:34].mean(axis=1)
bogra_1948

bogra_1948.describe()

bogra_1948.iloc[1]

"""## Making Datasets for each months"""

february = pd.DataFrame(bogra_1948.iloc[1])
february = february.reset_index()
february.rename(columns = {'index' : "Day"}, inplace = True)
february.rename(columns = {1 : 'Tempareture'}, inplace = True)
february.drop(february.head(3).index, inplace=True)
february = february.reset_index(drop = True)
february.head(5)

# march = pd.DataFrame(bogra_1948.iloc[2])
# march = march.reset_index()
# march.rename(columns = {"index" : "Day"}, inplace = True)
# march.rename(columns = {2 : 'Tempareture'}, inplace = True)
# march.drop(march.head(3).index, inplace=True)
# march = march.reset_index(drop = True)
# march.head(5)

# april = pd.DataFrame(bogra_1948.iloc[3])
# april = april.reset_index()
# april.rename(columns = {"index" : "Day"}, inplace = True)
# april.rename(columns = {3 : 'Tempareture'}, inplace = True)
# april.drop(april.head(3).index, inplace=True)
# april = april.reset_index(drop = True)
# april.head(5)

# may = pd.DataFrame(bogra_1948.iloc[4])
# may = may.reset_index()
# may.rename(columns = {"index" : "Day"}, inplace = True)
# may.rename(columns = {4 : 'Tempareture'}, inplace = True)
# may.drop(may.head(3).index, inplace=True)
# may = may.reset_index(drop = True)
# may.head(5)

# june = pd.DataFrame(bogra_1948.iloc[5])
# june = june.reset_index()
# june.rename(columns = {"index" : "Day"}, inplace = True)
# june.rename(columns = {5 : 'Tempareture'}, inplace = True)
# june.drop(june.head(3).index, inplace=True)
# june = june.reset_index(drop = True)
# june.head(5)

# july = pd.DataFrame(bogra_1948.iloc[6])
# july = july.reset_index()
# july.rename(columns = {"index" : "Day"}, inplace = True)
# july.rename(columns = {6 : 'Tempareture'}, inplace = True)
# july.drop(july.head(3).index, inplace=True)
# july = july.reset_index(drop = True)
# july.head(5)

# august = pd.DataFrame(bogra_1948.iloc[7])
# august = august.reset_index()
# august.rename(columns = {"index" : "Day"}, inplace = True)
# august.rename(columns = {7 : 'Tempareture'}, inplace = True)
# august.drop(august.head(3).index, inplace=True)
# august = august.reset_index(drop = True)
# august.head(5)

# september = pd.DataFrame(bogra_1948.iloc[8])
# september = september.reset_index()
# september.rename(columns = {"index" : "Day"}, inplace = True)
# september.rename(columns = {8 : 'Tempareture'}, inplace = True)
# september.drop(september.head(3).index, inplace=True)
# september = september.reset_index(drop = True)
# september.head(5)

# october = pd.DataFrame(bogra_1948.iloc[9])
# october = october.reset_index()
# october.rename(columns = {"index" : "Day"}, inplace = True)
# october.rename(columns = {9 : 'Tempareture'}, inplace = True)
# october.drop(october.head(3).index, inplace=True)
# october = october.reset_index(drop = True)
# october.head(5)

# november = pd.DataFrame(bogra_1948.iloc[10])
# november = november.reset_index()
# november.rename(columns = {"index" : "Day"}, inplace = True)
# november.rename(columns = {10 : 'Tempareture'}, inplace = True)
# november.drop(november.head(3).index, inplace=True)
# november = november.reset_index(drop = True)
# november.head(5)

# december = pd.DataFrame(bogra_1948.iloc[11])
# december = december.reset_index()
# december.rename(columns = {"index" : "Day"}, inplace = True)
# december.rename(columns = {11 : 'Tempareture'}, inplace = True)
# december.drop(december.head(3).index, inplace=True)
# december = december.reset_index(drop = True)
# december.head(5)

"""## Ploting all the months togather"""

# plt.plot(february['Day'], february['Tempareture'], color= 'green', label= 'February')
# plt.plot(march['Day'], march['Tempareture'], color= 'blue', label= 'March')
# plt.plot(april['Day'], april['Tempareture'], color= 'red', label= 'April')
# plt.plot(may['Day'], may['Tempareture'], color= 'yellow', label= 'May')
# plt.plot(june['Day'], june['Tempareture'], color= 'orange', label= 'June')
# plt.plot(july['Day'], july['Tempareture'], color= 'black', label= 'July')
# plt.plot(august['Day'], august['Tempareture'], color= 'purple', label= 'August')
# plt.plot(september['Day'], september['Tempareture'], color= 'orchid', label= 'September')
# plt.plot(october['Day'], october['Tempareture'], color= 'palevioletred', label= 'October')
# plt.plot(november['Day'], november['Tempareture'], color= 'teal', label= 'November')
# plt.plot(december['Day'], december['Tempareture'], color= 'violet', label= 'December')
# plt.title("Tempareture of Bogra in 1948")
# plt.xticks(['5', '10','15', '20','25','30'])
# plt.xlabel('Day')
# plt.ylabel('Tempareture')
# plt.legend()

# plt.scatter(february['Day'], february['Tempareture'], color= 'green', label= 'February')
# plt.scatter(march['Day'], march['Tempareture'], color= 'blue', label= 'March')
# plt.scatter(april['Day'], april['Tempareture'], color= 'red', label= 'April')
# plt.scatter(may['Day'], may['Tempareture'], color= 'yellow', label= 'May')
# plt.scatter(june['Day'], june['Tempareture'], color= 'orange', label= 'June')
# plt.scatter(july['Day'], july['Tempareture'], color= 'black', label= 'July')
# plt.scatter(august['Day'], august['Tempareture'], color= 'purple', label= 'August')
# plt.scatter(september['Day'], september['Tempareture'], color= 'orchid', label= 'September')
# plt.scatter(october['Day'], october['Tempareture'], color= 'palevioletred', label= 'October')
# plt.scatter(november['Day'], november['Tempareture'], color= 'teal', label= 'November')
# plt.scatter(december['Day'], december['Tempareture'], color= 'violet', label= 'December')
# plt.title("Tempareture of Bogra in 1948")
# # plt.xticks(['5', '10','15', '20','25','30'])
# plt.xlabel('Day')
# plt.ylabel('Tempareture')
# plt.legend()

# plt.plot(bogra_1948['Month\Date'], bogra_1948['Tempareture of the month'])

# plt.scatter(bogra_1948['Month\Date'], bogra_1948['Tempareture of the month'])

# plt.plot(february['Day'], february['Tempareture'], color= 'green', label= 'Maximum')
# plt.title("Tempareture of Bogra February in 1948")
# plt.xticks(['5', '10','15', '20','25','30'])
# plt.xlabel('Day')
# plt.ylabel('Tempareture')
# plt.legend()
# # plt.show()

# plt.scatter(february['Day'], february['Tempareture'], color= 'green', label= 'Maximum')
# plt.title("Tempareture of Bogra of February in 1948")
# plt.xticks(['5', '10','15', '20','25','30'])
# plt.xlabel('Day')
# plt.ylabel('Tempareture')
# plt.legend()
# # plt.show()
